updated yml file

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,11 +9,23 @@ steps:
       ls -l src/main/resources/
     displayName: 'List contents of resources directory'
 
+  - script: |
+      if [ ! -s "src/main/resources/Test_Data.xls" ]; then
+        echo "Error: src/main/resources/Test_Data.xls is empty or does not exist."
+        exit 1
+      fi
+    displayName: 'Check if Test_Data.xls is not empty'
+
   - task: CopyFiles@2
     inputs:
       SourceFolder: '$(Build.SourcesDirectory)/src/main/resources'
       Contents: 'Test_Data.xls'
       TargetFolder: '$(Build.ArtifactStagingDirectory)/resources'
+
+  - task: PublishBuildArtifacts@1
+    inputs:
+      PathtoPublish: '$(Build.ArtifactStagingDirectory)/resources'
+      ArtifactName: 'resources'
 
   - task: Maven@3
     displayName: 'Maven pom.xml'
